export const RuleComponentTypeConstant = {
  PUPA_RULE_SET: 2,
  RULES_PARENT: 3,
  PUPA_RULE: 5,

  CONDITION_PARENT: 6,
  CONDITION_SIMPLE: 7,
  CONDITION_AND: 8,
  CONDITION_OR: 9,

  ACTION_PARENT: 10,
  ACTION_SIMPLE: 11
};
